<a href="https://colab.research.google.com/github/Sinchana-Chaluvaraju/NumPy/blob/main/NumPy(basic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy

In [3]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
print(np.__version__)

1.25.2


In [6]:
#creating arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#by using a tuple we can create an NumPy array
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [8]:
#Dimensions in an array
#0-D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [9]:
#1-D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [11]:
#2-D array
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
#3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [18]:
#How to check number of dimensions
import numpy as np
arr1 = np.array(42)
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3,4], [5,6,7,8]])
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [20]:
#Higher Dimensional Array
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


In [21]:
#Access Array Elements
#Access first Element
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[0])

1


In [22]:
#Access Second Element
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[1])

2


In [ ]:
#Access 2nd and 3rd Element and add them
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[2] + arr[3])

7


In [23]:
#Access 2nd and 3rd Element and add them
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[2] + arr[3])

7


In [26]:
#Access 3rd and 4th Element
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[3], arr[4])

4 4
