<a href="https://colab.research.google.com/github/Sinchana-Chaluvaraju/NumPy/blob/main/NumPy(basic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy

In [ ]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
#creating arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#by using a tuple we can create an NumPy array
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [ ]:
#Dimensions in an array
#0-D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
#1-D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
#2-D array
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
#How to check number of dimensions
import numpy as np
arr1 = np.array(42)
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3,4], [5,6,7,8]])
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [ ]:
#Higher Dimensional Array
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


In [ ]:
#Access Array Elements
#Access first Element
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[0])

1


In [ ]:
#Access Second Element
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[1])

2


In [ ]:
#Access 2nd and 3rd Element and add them
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[2] + arr[3])

7


In [ ]:
#Access 2nd and 3rd Element and add them
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[2] + arr[3])

7


In [ ]:
#Access 3rd and 4th Element
import numpy as np
arr = np.array([1,2,3,4,4,5,6,9])
print(arr[3], arr[4])

4 4


In [ ]:
#Access 2-D Array
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element on 1st row:", arr[0,1])

2nd element on 1st row: 2


In [ ]:
#Access 2-D Array
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element on 2st row:", arr[1,1])

2nd element on 2st row: 7


In [ ]:
#Access 3-D Array
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12], [13,14,15,16]]])
print(arr[0,0,2])

3


In [ ]:
#Negative Indexing
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Last element from 2nd dim:", arr[1, -1])

Last element from 2nd dim: 10


In [ ]:
#Slicing arrays
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
#Negative Slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [ ]:
#Slicing 2-D Arrays
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
#Data Type of an array
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [ ]:
import numpy as np
arr = np.array(["Apple", "Banana", "Cherry"])
print(arr.dtype)

<U6


In [ ]:
import numpy as np
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np
arr = np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
import numpy as np
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
import numpy as np
arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
#Numpy copy
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#numpy view
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#making changes in the view
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 32

print(arr)
print(x)

[32  2  3  4  5]
[32  2  3  4  5]


In [ ]:
#checking if array owns its data
import numpy as np
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
